### ISSUE TITLE
Question about editing .wtp and .uid files Folder UI

### ISSUE THREAD

**Issue by Digote** [cabalex/astral-extractor#3]
Hi, sorry for my bad english.

Is there any way to edit .uid and .wtp files from the Astral Chain UI folder.
Because I'm only able to edit the 3D models from other folders, but when I try the interface part, the available programs (Switch tools box or Noesis) can't open.
Sorry if this question is not in accordance with any rule, and that you understand a lot about the extraction part of the game.

![Extraido-dtt](https://user-images.githubusercontent.com/45742711/209818482-9b19459c-834a-4880-a9f6-eec95954527a.png)

![Extraido-dat](https://user-images.githubusercontent.com/45742711/209818485-9218dc8c-fc16-4ddf-a998-4986a8b1eb49.png)

**Comment by cabalex** [comment]
Sorry for the late reply!

**.UID files aren't currently extractable** since there's barely any documentation about what they do, but they don't really matter too much. There's not much important data stored in them, and I'm not really sure what they're used for.

**.WTP files are raw texture data** that are always paired with .WTA (texture header data) files. .WTA/.WTP files are always in pairs (although sometimes they are split between DAT/DTT: for example, em00a0.wta is in em00a0.dat, but em00a0.wtp is in em00a0.dtt).
You can actually open them in Switch Toolbox by putting both the WTA and WTP files in the same directory, and opening the WTA file. Alternatively, you can edit these WTA/WTP files by opening them in [my fork of NieR2Blender2NieR](https://github.com/cabalex/NieR2Blender2NieR).

Side note: Noesis is generally only for previewing 3D models, such as the DAT/DTT pairs in em/, pl/, etc. As such, you won't have luck using it on folders like core/ or ui/.

**Comment by Digote** [comment]
thank you very much for the explanation, it will help me a lot.
